### ISSUE TITLE
The importer not working

### ISSUE THREAD

**Issue by Brindha-Lekshmisaran** [James-Quigley/glo-trello-import#2]
Hi,
I keyed in the Trello API and token. I couldn't find info on how to get gitkraken API key from their website. I got a gitkraken board API key from https://app.gitkraken.com/api/glo/boards/ (as advised in https://github.com/Oj18/glopi).

While the Trello API/token works and populates the list of boards, the gitkraken API token does obtained from the above link for the board does not seem to work. Nothing happens after I click import. Can you let me know if I am going about it the wrong way perhaps?

Many thanks,
Brindha

**Comment by koverda** [comment]
i believe the api url needs to change to https://gloapi.gitkraken.com/v1/glo/

but then there are issues with the labels
